package com.jingshanghui.pos.saas.migration;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import java.sql.*;
import java.util.Set;

import static org.assertj.core.api.Assertions.*;

/** 在干净 MySQL 8.4 验证 SaaS V81-V82、中文注释、只追加历史和原子配额。 */
@Tag("local")
class SaasMigrationMySqlIT {
    private final String url=required("GATE8A_SAA_MYSQL_JDBC_URL"),username=required("GATE8A_SAA_MYSQL_USERNAME"),password=required("GATE8A_SAA_MYSQL_PASSWORD");
    @Test void migratesThroughV82AndEnforcesSaasOwnerGuards() throws Exception {
        createMenuFixture();Flyway flyway=Flyway.configure().dataSource(url,username,password).locations("classpath:db/migration").table("jshpos_flyway_schema_history").baselineOnMigrate(true).baselineVersion("0").cleanDisabled(true).load();
        assertThat(flyway.migrate().migrationsExecuted).isPositive();assertThat(flyway.migrate().migrationsExecuted).isZero();flyway.validate();assertThat(flyway.info().current().getVersion().toString()).isEqualTo("202608230082");assertSchemaAndComments();assertAppendOnlyAndQuota();
    }
    private void createMenuFixture() throws SQLException {try(Connection c=DriverManager.getConnection(url,username,password);Statement s=c.createStatement()){s.executeUpdate("CREATE TABLE IF NOT EXISTS sys_menu(menu_id BIGINT NOT NULL PRIMARY KEY,menu_name VARCHAR(50) NOT NULL,parent_id BIGINT DEFAULT 0,order_num INT DEFAULT 0,path VARCHAR(200) DEFAULT '',component VARCHAR(255),query_param VARCHAR(255),route_name VARCHAR(100),is_frame INT DEFAULT 1,is_cache INT DEFAULT 0,menu_type CHAR(1) DEFAULT '',visible CHAR(1) DEFAULT '0',status CHAR(1) DEFAULT '0',perms VARCHAR(100),icon VARCHAR(100) DEFAULT '#',create_dept BIGINT,create_by BIGINT,create_time DATETIME,update_by BIGINT,update_time DATETIME,remark VARCHAR(500) DEFAULT '') ENGINE=InnoDB");}}
    private void assertSchemaAndComments() throws SQLException {Set<String> tables=Set.of("saas_plan","saas_merchant_application","saas_application_state_event","saas_entitlement_version","saas_entitlement_item","saas_tenant_entitlement","saas_tenant_lifecycle_event","saas_initialization_checkpoint","saas_command_result","saas_quota_usage","saas_audit_event","saas_outbox");try(Connection c=DriverManager.getConnection(url,username,password);Statement s=c.createStatement()){for(String table:tables)try(ResultSet r=c.getMetaData().getTables(c.getCatalog(),null,table,new String[]{"TABLE"})){assertThat(r.next()).as(table).isTrue();}try(ResultSet r=s.executeQuery("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name IN ('"+String.join("','",tables)+"') AND column_comment=''")){assertThat(r.next()).isTrue();assertThat(r.getInt(1)).isZero();}try(ResultSet r=s.executeQuery("SELECT COUNT(DISTINCT perms) FROM sys_menu WHERE menu_id BETWEEN 9201700 AND 9201712")){assertThat(r.next()).isTrue();assertThat(r.getInt(1)).isEqualTo(13);}}}
    private void assertAppendOnlyAndQuota() throws SQLException {try(Connection c=DriverManager.getConnection(url,username,password);Statement s=c.createStatement()){s.executeUpdate("INSERT INTO saas_plan(plan_id,plan_code,plan_name,platform_package_id,account_limit,status,created_at,updated_at) VALUES(1,'V1','虚构套餐',1,50,'ACTIVE',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))");s.executeUpdate("INSERT INTO saas_entitlement_version(version_id,plan_id,version_no,state,effective_at,content_sha256,creator_user_id,record_version,created_at,updated_at) VALUES('01K80000000000000000000001',1,1,'EFFECTIVE',UTC_TIMESTAMP(3)-INTERVAL 1 DAY,REPEAT('a',64),1,0,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))");s.executeUpdate("INSERT INTO saas_entitlement_item(item_id,version_id,feature_code,enabled_flag,quota_limit,item_sha256) VALUES('01K80000000000000000000002','01K80000000000000000000001','STORE_COUNT',TRUE,2,REPEAT('b',64))");s.executeUpdate("INSERT INTO saas_merchant_application(application_id,application_code,tenant_id,technical_tenant_id,company_name,industry,plan_id,state,submitter_user_id,approver_user_id,record_version,content_sha256,created_at,updated_at) VALUES('01K80000000000000000000003','APP-001','TENANT_A',9,'虚构商户','CONVENIENCE',1,'ACTIVE',1,2,4,REPEAT('c',64),UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))");s.executeUpdate("INSERT INTO saas_application_state_event(event_id,application_id,tenant_id,from_state,to_state,request_sha256,correlation_id,actor_user_id,occurred_at) VALUES('01K80000000000000000000004','01K80000000000000000000003','TENANT_A','INITIALIZING','ACTIVE',REPEAT('d',64),'trace-001',2,UTC_TIMESTAMP(3))");assertThatThrownBy(()->s.executeUpdate("DELETE FROM saas_application_state_event WHERE event_id='01K80000000000000000000004'")).isInstanceOf(SQLException.class).hasMessageContaining("cannot be deleted");s.executeUpdate("INSERT INTO saas_tenant_entitlement(tenant_id,plan_id,version_id,lifecycle_state,lifecycle_version,binding_sha256,created_at,updated_at) VALUES('TENANT_A',1,'01K80000000000000000000001','ACTIVE',1,REPEAT('e',64),UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))");s.executeUpdate("INSERT INTO saas_quota_usage(tenant_id,feature_code,used_count,quota_limit,updated_at) VALUES('TENANT_A','STORE_COUNT',1,2,UTC_TIMESTAMP(3))");assertThat(s.executeUpdate("UPDATE saas_quota_usage SET used_count=used_count+1 WHERE tenant_id='TENANT_A' AND feature_code='STORE_COUNT' AND used_count+1<=quota_limit")).isEqualTo(1);assertThat(s.executeUpdate("UPDATE saas_quota_usage SET used_count=used_count+1 WHERE tenant_id='TENANT_A' AND feature_code='STORE_COUNT' AND used_count+1<=quota_limit")).isZero();}}
    private static String required(String name){String v=System.getenv(name);if(v==null||v.isBlank())throw new IllegalStateException(name+" must be provided by CI");return v;}
}
