CREATE TABLE upg_release (
  release_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '服务端发布ULID',
  tenant_id VARCHAR(20) NOT NULL COMMENT '可信上下文注入的租户标识',
  artifact_type VARCHAR(24) NOT NULL COMMENT '发布物类型：SERVER WEB MYSQL_SCHEMA SQLITE_SCHEMA TEMPLATE_PACKAGE DATA_PACKAGE APK',
  release_version VARCHAR(64) NOT NULL COMMENT '发布物语义版本',
  channel_code VARCHAR(16) NOT NULL COMMENT '通道：INTERNAL CANARY STABLE EMERGENCY',
  object_key VARCHAR(512) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'releases/tenant/release范围内私有对象键',
  artifact_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '发布物SHA-256',
  signature_base64 VARCHAR(1024) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '受控构建签名Base64；不含私钥',
  key_version VARCHAR(64) NOT NULL COMMENT '外部签名密钥版本引用',
  build_commit CHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '构建Git完整提交SHA',
  sbom_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '对应SBOM文件SHA-256',
  manifest_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '规范发布清单SHA-256',
  min_app_version VARCHAR(32) NOT NULL COMMENT '最低兼容应用版本',
  max_app_version VARCHAR(32) NOT NULL COMMENT '最高兼容应用版本',
  min_protocol_version VARCHAR(32) NOT NULL COMMENT '最低兼容协议版本',
  max_protocol_version VARCHAR(32) NOT NULL COMMENT '最高兼容协议版本',
  min_schema_version VARCHAR(32) NOT NULL COMMENT '最低兼容Schema版本',
  max_schema_version VARCHAR(32) NOT NULL COMMENT '最高兼容Schema版本',
  min_system_version VARCHAR(32) NOT NULL COMMENT '最低兼容系统版本',
  max_system_version VARCHAR(32) NOT NULL COMMENT '最高兼容系统版本',
  required_capability_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '可选终端能力快照摘要',
  state VARCHAR(16) NOT NULL COMMENT '发布状态：DRAFT SIGNED STAGED REVOKED',
  request_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '创建命令规范SHA-256',
  created_by BIGINT NOT NULL COMMENT '可信创建用户ID',
  last_actor_id BIGINT NULL COMMENT '最近状态变更用户ID',
  correlation_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '创建关联ULID',
  last_correlation_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '最近变更关联ULID',
  version_no BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态乐观锁版本',
  created_at DATETIME(3) NOT NULL COMMENT '创建UTC时刻',
  updated_at DATETIME(3) NOT NULL COMMENT '最近状态变更UTC时刻',
  PRIMARY KEY (release_id),
  UNIQUE KEY uk_upg_release_version (tenant_id,artifact_type,channel_code,release_version),
  UNIQUE KEY uk_upg_release_object (tenant_id,object_key),
  KEY idx_upg_release_state (tenant_id,state,artifact_type,created_at),
  CONSTRAINT ck_upg_release_type CHECK (artifact_type IN ('SERVER','WEB','MYSQL_SCHEMA','SQLITE_SCHEMA','TEMPLATE_PACKAGE','DATA_PACKAGE','APK')),
  CONSTRAINT ck_upg_release_channel CHECK (channel_code IN ('INTERNAL','CANARY','STABLE','EMERGENCY')),
  CONSTRAINT ck_upg_release_state CHECK (state IN ('DRAFT','SIGNED','STAGED','REVOKED'))
) ENGINE=InnoDB COMMENT='Gate 6B发布物身份与受控状态；CONTROLLED_WRITE/XML；签名后身份冻结';

CREATE TABLE upg_target_scope (
  scope_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '服务端范围ULID',
  tenant_id VARCHAR(20) NOT NULL COMMENT '可信租户标识',
  aggregate_type VARCHAR(16) NOT NULL COMMENT '范围所属：RELEASE或ROLLOUT',
  aggregate_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '发布或灰度批次ULID',
  store_id BIGINT NOT NULL COMMENT '受权目标门店ID',
  created_at DATETIME(3) NOT NULL COMMENT '范围写入UTC时刻',
  PRIMARY KEY (scope_id),
  UNIQUE KEY uk_upg_scope (tenant_id,aggregate_type,aggregate_id,store_id),
  KEY idx_upg_scope_store (tenant_id,store_id,aggregate_type),
  CONSTRAINT ck_upg_scope_type CHECK (aggregate_type IN ('RELEASE','ROLLOUT')),
  CONSTRAINT ck_upg_scope_store CHECK (store_id>0)
) ENGINE=InnoDB COMMENT='Gate 6B只追加发布门店范围；APPEND_ONLY/XML';

CREATE TABLE upg_rollout (
  rollout_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '服务端灰度批次ULID',
  tenant_id VARCHAR(20) NOT NULL COMMENT '可信租户标识',
  release_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '已STAGED发布ULID',
  canary_percent TINYINT UNSIGNED NOT NULL COMMENT '首轮灰度百分比1至25',
  state VARCHAR(16) NOT NULL COMMENT '状态：PLANNED CANARY ROLLING PAUSED COMPLETED FAILED',
  request_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '创建批次命令SHA-256',
  created_by BIGINT NOT NULL COMMENT '可信创建用户ID',
  last_actor_id BIGINT NULL COMMENT '最近状态变更用户ID',
  correlation_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '创建关联ULID',
  last_correlation_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '最近变更关联ULID',
  version_no BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态乐观锁版本',
  created_at DATETIME(3) NOT NULL COMMENT '创建UTC时刻',
  updated_at DATETIME(3) NOT NULL COMMENT '最近状态变更UTC时刻',
  PRIMARY KEY (rollout_id),
  UNIQUE KEY uk_upg_rollout_request (tenant_id,request_sha256),
  KEY idx_upg_rollout_release (tenant_id,release_id,state,created_at),
  CONSTRAINT fk_upg_rollout_release FOREIGN KEY (release_id) REFERENCES upg_release(release_id),
  CONSTRAINT ck_upg_rollout_percent CHECK (canary_percent BETWEEN 1 AND 25),
  CONSTRAINT ck_upg_rollout_state CHECK (state IN ('PLANNED','CANARY','ROLLING','PAUSED','COMPLETED','FAILED'))
) ENGINE=InnoDB COMMENT='Gate 6B灰度编排控制记录；CONTROLLED_WRITE/XML';

CREATE TABLE upg_terminal_task (
  task_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '服务端终端任务ULID',
  tenant_id VARCHAR(20) NOT NULL COMMENT '可信租户标识',
  rollout_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '所属灰度批次ULID',
  release_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '冻结发布ULID',
  device_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '终端注册表设备ULID',
  store_id BIGINT NOT NULL COMMENT '终端注册表可信门店ID',
  state VARCHAR(32) NOT NULL COMMENT 'PLANNED DOWNLOADING VERIFIED INSTALLING HEALTH_CHECK SUCCEEDED ROLLED_BACK FORWARD_FIX_REQUIRED FAILED_CLOSED',
  request_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '分配命令SHA-256',
  last_evidence_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '最近去敏软件执行证据SHA-256',
  created_by BIGINT NOT NULL COMMENT '可信创建用户ID',
  last_actor_id BIGINT NULL COMMENT '最近状态变更用户ID',
  correlation_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '创建关联ULID',
  last_correlation_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '最近变更关联ULID',
  version_no BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态乐观锁版本',
  created_at DATETIME(3) NOT NULL COMMENT '创建UTC时刻',
  updated_at DATETIME(3) NOT NULL COMMENT '最近状态变更UTC时刻',
  PRIMARY KEY (task_id),
  UNIQUE KEY uk_upg_task_device (tenant_id,rollout_id,device_id),
  KEY idx_upg_task_state (tenant_id,rollout_id,state,updated_at),
  CONSTRAINT fk_upg_task_rollout FOREIGN KEY (rollout_id) REFERENCES upg_rollout(rollout_id),
  CONSTRAINT fk_upg_task_release FOREIGN KEY (release_id) REFERENCES upg_release(release_id),
  CONSTRAINT ck_upg_task_store CHECK (store_id>0),
  CONSTRAINT ck_upg_task_state CHECK (state IN ('PLANNED','DOWNLOADING','VERIFIED','INSTALLING','HEALTH_CHECK','SUCCEEDED','ROLLED_BACK','FORWARD_FIX_REQUIRED','FAILED_CLOSED'))
) ENGINE=InnoDB COMMENT='Gate 6B终端软件任务状态；CONTROLLED_WRITE/XML；不代表真实厂商远程命令';

CREATE TABLE upg_command_result (
  command_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '服务端命令结果ULID',
  tenant_id VARCHAR(20) NOT NULL COMMENT '可信租户标识',
  command_type VARCHAR(32) NOT NULL COMMENT '稳定命令类型',
  idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '租户命令类型内幂等键',
  request_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '规范请求SHA-256；同键异内容拒绝',
  aggregate_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '命令结果聚合ULID',
  result_code VARCHAR(32) NOT NULL COMMENT '稳定结果状态码',
  actor_id BIGINT NOT NULL COMMENT '可信命令操作者ID',
  occurred_at DATETIME(3) NOT NULL COMMENT '命令生效UTC时刻',
  PRIMARY KEY (command_id),
  UNIQUE KEY uk_upg_command (tenant_id,command_type,idempotency_key),
  KEY idx_upg_command_aggregate (tenant_id,aggregate_id,occurred_at)
) ENGINE=InnoDB COMMENT='Gate 6B只追加命令幂等结果；APPEND_ONLY/XML';

CREATE TABLE upg_release_event (
  event_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '服务端发布事件ULID',
  tenant_id VARCHAR(20) NOT NULL COMMENT '可信租户标识',
  aggregate_type VARCHAR(16) NOT NULL COMMENT '聚合类型：RELEASE ROLLOUT TASK',
  aggregate_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '相关聚合ULID',
  event_type VARCHAR(48) NOT NULL COMMENT '版本化前的内部稳定事件类型',
  from_state VARCHAR(32) NULL COMMENT '原状态；创建事件为空',
  to_state VARCHAR(32) NOT NULL COMMENT '目标状态',
  evidence_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '不含Secret或PII的证据SHA-256',
  correlation_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '端到端关联ULID',
  occurred_at DATETIME(3) NOT NULL COMMENT '事件发生UTC时刻',
  PRIMARY KEY (event_id),
  KEY idx_upg_event_aggregate (tenant_id,aggregate_type,aggregate_id,occurred_at),
  CONSTRAINT ck_upg_event_aggregate CHECK (aggregate_type IN ('RELEASE','ROLLOUT','TASK'))
) ENGINE=InnoDB COMMENT='Gate 6B只追加发布领域事件；APPEND_ONLY/XML';

CREATE TABLE upg_audit (
  audit_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '服务端发布审计ULID',
  tenant_id VARCHAR(20) NOT NULL COMMENT '可信租户标识',
  aggregate_type VARCHAR(16) NOT NULL COMMENT '聚合类型：RELEASE ROLLOUT TASK',
  aggregate_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '相关聚合ULID',
  action_code VARCHAR(48) NOT NULL COMMENT '稳定审计动作码',
  before_state VARCHAR(32) NULL COMMENT '动作前状态',
  after_state VARCHAR(32) NOT NULL COMMENT '动作后状态',
  evidence_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '去敏证据SHA-256',
  actor_id BIGINT NOT NULL COMMENT '可信操作者ID',
  correlation_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '端到端关联ULID',
  occurred_at DATETIME(3) NOT NULL COMMENT '动作发生UTC时刻',
  PRIMARY KEY (audit_id),
  KEY idx_upg_audit_aggregate (tenant_id,aggregate_type,aggregate_id,occurred_at),
  CONSTRAINT ck_upg_audit_aggregate CHECK (aggregate_type IN ('RELEASE','ROLLOUT','TASK'))
) ENGINE=InnoDB COMMENT='Gate 6B只追加发布审计；APPEND_ONLY/XML';
