name: pos_device_adapter
description: 鲸熵汇 POS Android 设备适配边界
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: 3.47.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jingshanghui.pos.pos_device_adapter
        pluginClass: PosDeviceAdapterPlugin
