CREATE TABLE bak_backup_set (
  backup_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '服务端备份ULID及幂等键',
  environment_code VARCHAR(64) NOT NULL COMMENT '备份来源环境标识；不含密钥或口令',
  tenant_ids_csv TEXT NOT NULL COMMENT '服务端授权并排序的租户标识集合；仅用于恢复范围核对',
  tenant_scope_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '排序租户集合SHA-256；对象命名空间与恢复授权边界',
  point_in_time DATETIME(3) NOT NULL COMMENT '恢复点UTC；PITR目标边界',
  latest_included_fact_at DATETIME(3) NOT NULL COMMENT '最后纳入权威事实的UTC时刻；用于自动计算RPO',
  schema_version VARCHAR(64) NOT NULL COMMENT '备份时权威数据库Schema版本',
  application_version VARCHAR(64) NOT NULL COMMENT '备份时服务端应用版本',
  key_version VARCHAR(64) NOT NULL COMMENT '外部KMS或独立密钥版本引用；不保存密钥材料',
  immutable_until DATETIME(3) NOT NULL COMMENT '不可变保留截止UTC；生产删除身份不得提前删除',
  request_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '规范创建命令SHA-256；同键异内容拒绝',
  manifest_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT 'AVAILABLE清单规范JSON SHA-256',
  manifest_json LONGTEXT NULL COMMENT '不含密钥与明文数据的规范恢复清单JSON',
  failure_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '去敏失败类型SHA-256；不保存异常原文或Secret',
  state VARCHAR(16) NOT NULL COMMENT '状态：CREATING AVAILABLE FAILED EXPIRED',
  requested_by BIGINT NOT NULL COMMENT '可信备份操作者用户标识',
  last_actor_id BIGINT NULL COMMENT '最后状态迁移的可信操作者用户标识',
  correlation_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '创建链路关联ULID',
  last_correlation_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '最后状态迁移关联ULID',
  version INT NOT NULL DEFAULT 0 COMMENT '受控状态迁移乐观锁版本',
  created_at DATETIME(3) NOT NULL COMMENT '目录登记UTC时刻',
  updated_at DATETIME(3) NOT NULL COMMENT '最后状态迁移UTC时刻',
  PRIMARY KEY (backup_id),
  UNIQUE KEY uk_bak_request (request_sha256),
  KEY idx_bak_scope_point (tenant_scope_sha256,point_in_time,state),
  KEY idx_bak_retention (state,immutable_until),
  CONSTRAINT ck_bak_time CHECK (latest_included_fact_at<=point_in_time AND immutable_until>point_in_time),
  CONSTRAINT ck_bak_state CHECK (state IN ('CREATING','AVAILABLE','FAILED','EXPIRED')),
  CONSTRAINT ck_bak_manifest CHECK ((state='AVAILABLE' AND manifest_sha256 IS NOT NULL AND manifest_json IS NOT NULL) OR state<>'AVAILABLE')
) ENGINE=InnoDB COMMENT='Gate 6A加密恢复集合目录；CONTROLLED_WRITE/XML；不承载业务事实';

CREATE TABLE bak_backup_object (
  object_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '服务端对象目录ULID',
  backup_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '所属备份ULID',
  data_class VARCHAR(24) NOT NULL COMMENT '数据类别：MYSQL BUSINESS_OBJECT CONFIG TEMPLATE MIGRATION EVIDENCE',
  logical_name VARCHAR(256) NOT NULL COMMENT '受白名单约束的逻辑路径；不作为文件系统绝对路径',
  media_type VARCHAR(64) NOT NULL COMMENT '对象媒体类型',
  tenant_scope_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '对象租户范围SHA-256；必须与备份清单一致',
  plaintext_size_bytes BIGINT UNSIGNED NOT NULL COMMENT '加密前明文字节数',
  plaintext_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '加密前明文SHA-256；恢复后复核',
  ciphertext_size_bytes BIGINT UNSIGNED NOT NULL COMMENT '含nonce与GCM tag的密文字节数',
  ciphertext_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '存储密文SHA-256；下载后解密前复核',
  key_version VARCHAR(64) NOT NULL COMMENT '独立解密密钥版本引用',
  nonce_base64 VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'AES-GCM随机96位nonce的Base64表示',
  object_key VARCHAR(256) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'backups/范围摘要/backupId/密文摘要.aead只追加对象键',
  created_at DATETIME(3) NOT NULL COMMENT '对象目录写入UTC时刻',
  PRIMARY KEY (object_id),
  UNIQUE KEY uk_bak_object_name (backup_id,logical_name),
  UNIQUE KEY uk_bak_object_key (object_key),
  KEY idx_bak_object_scope (tenant_scope_sha256,backup_id,data_class),
  CONSTRAINT fk_bak_object_set FOREIGN KEY (backup_id) REFERENCES bak_backup_set(backup_id),
  CONSTRAINT ck_bak_object_class CHECK (data_class IN ('MYSQL','BUSINESS_OBJECT','CONFIG','TEMPLATE','MIGRATION','EVIDENCE')),
  CONSTRAINT ck_bak_object_size CHECK (plaintext_size_bytes>0 AND ciphertext_size_bytes>plaintext_size_bytes)
) ENGINE=InnoDB COMMENT='Gate 6A只追加加密对象目录；APPEND_ONLY/XML；密钥材料不入库';

CREATE TABLE bak_restore_drill (
  drill_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '恢复演练ULID及幂等键',
  backup_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '被恢复备份ULID',
  request_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '规范恢复命令SHA-256；同键异内容拒绝',
  state VARCHAR(16) NOT NULL COMMENT '状态：RUNNING PASS FAIL_CLOSED',
  started_at DATETIME(3) NOT NULL COMMENT '自动计时开始UTC；空隔离目标初始化前',
  ended_at DATETIME(3) NULL COMMENT '完成或失败关闭UTC',
  rpo_seconds BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '恢复点与最后纳入事实的秒差；内部目标不超过900秒',
  rto_seconds BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '从开始到核对完成的自动计时秒数；内部目标不超过3600秒',
  evidence_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '规范演练证据SHA-256',
  requested_by BIGINT NOT NULL COMMENT '可信恢复操作者用户标识',
  last_actor_id BIGINT NULL COMMENT '结束演练的可信操作者用户标识',
  correlation_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '创建链路关联ULID',
  last_correlation_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '结束链路关联ULID',
  version INT NOT NULL DEFAULT 0 COMMENT '状态迁移乐观锁版本',
  PRIMARY KEY (drill_id),
  UNIQUE KEY uk_bak_drill_request (request_sha256),
  KEY idx_bak_drill_backup (backup_id,started_at,state),
  CONSTRAINT fk_bak_drill_set FOREIGN KEY (backup_id) REFERENCES bak_backup_set(backup_id),
  CONSTRAINT ck_bak_drill_state CHECK (state IN ('RUNNING','PASS','FAIL_CLOSED')),
  CONSTRAINT ck_bak_drill_time CHECK (ended_at IS NULL OR ended_at>=started_at),
  CONSTRAINT ck_bak_drill_evidence CHECK ((state='RUNNING' AND ended_at IS NULL) OR (state<>'RUNNING' AND ended_at IS NOT NULL AND evidence_sha256 IS NOT NULL))
) ENGINE=InnoDB COMMENT='Gate 6A空环境恢复演练及RPO/RTO证据；CONTROLLED_WRITE/XML';

CREATE TABLE bak_restore_check (
  check_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '服务端恢复校验ULID',
  drill_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '所属恢复演练ULID',
  check_code VARCHAR(40) NOT NULL COMMENT 'MANIFEST SHA256 ENCRYPTION FLYWAY_VALIDATE PROJECTION_REBUILD TENANT_RECONCILIATION BUSINESS_DAY_RECONCILIATION CURSOR AUDIT',
  result VARCHAR(16) NOT NULL COMMENT '不可变校验结果：PASS或FAIL_CLOSED',
  evidence_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '去敏校验证据SHA-256',
  checked_at DATETIME(3) NOT NULL COMMENT '校验完成UTC时刻',
  PRIMARY KEY (check_id),
  UNIQUE KEY uk_bak_check (drill_id,check_code),
  CONSTRAINT fk_bak_check_drill FOREIGN KEY (drill_id) REFERENCES bak_restore_drill(drill_id),
  CONSTRAINT ck_bak_check_result CHECK (result IN ('PASS','FAIL_CLOSED'))
) ENGINE=InnoDB COMMENT='Gate 6A只追加恢复校验明细；APPEND_ONLY/XML';

CREATE TABLE bak_audit (
  audit_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '服务端备份审计ULID',
  backup_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '相关备份ULID',
  drill_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '相关恢复演练ULID',
  action_code VARCHAR(40) NOT NULL COMMENT 'BACKUP_RESERVED BACKUP_AVAILABLE BACKUP_FAILED RESTORE_STARTED RESTORE_PASS RESTORE_FAIL_CLOSED',
  actor_id BIGINT NOT NULL COMMENT '可信操作者用户标识',
  correlation_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '端到端关联ULID',
  evidence_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '不含Secret和PII的动作证据SHA-256',
  occurred_at DATETIME(3) NOT NULL COMMENT '动作发生UTC时刻',
  PRIMARY KEY (audit_id),
  KEY idx_bak_audit_backup (backup_id,occurred_at),
  KEY idx_bak_audit_drill (drill_id,occurred_at)
) ENGINE=InnoDB COMMENT='Gate 6A只追加备份恢复审计；APPEND_ONLY/XML';
